using back_end.Context;
using back_end.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

// Load appsettings.json from API project
var config = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json")
    .Build();

var options = new DbContextOptionsBuilder<DBContext>()
    .UseSqlServer(config.GetConnectionString("DefaultConnection"))
    .Options;

using var db = new DBContext(options);

UserDB[] users = db.Users.ToArray();
if (users.Length > 0)
{
    Console.WriteLine("Admins:");
    foreach (UserDB user in users)
    {
        Console.WriteLine($"Name = {user.Name}; Email = {user.Email}");
    }
}

Console.Write("Admin name: ");
var name = Console.ReadLine();

Console.Write("Admin email: ");
var email = Console.ReadLine();

Console.Write("Admin password: ");
var password = Console.ReadLine();

if (db.Users.Any(u => u.Email == email))
{
    Console.WriteLine("Admin already exists.");
    return;
}

var hasher = new PasswordHasher<UserDB>();

var admin = new UserDB
{
    Id = Guid.NewGuid(),
    Email = email!,
    Name = name!,
    Roles = "Admin",
};

admin.HashedPassword = hasher.HashPassword(admin, password!);

db.Users.Add(admin);
db.SaveChanges();

Console.WriteLine("✅ Admin created successfully.");

