# max net8.0 $ docker image list
# i Info →   U  In Use
# IMAGE                                        ID             DISK USAGE   CONTENT SIZE   EXTRA
# mcr.microsoft.com/mssql/server:2022-latest   0ec7739e1c5e       2.25GB          600MB    U
# max net8.0 $
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Developer"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql_data:
